// <auto-generated />
namespace ElCaptain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedeliveryman : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedeliveryman));
        
        string IMigrationMetadata.Id
        {
            get { return "202101131401510_update-delivery-man"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
