// <auto-generated />
namespace ElCaptain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class gorejgiorjeiugrheuighreujigre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gorejgiorjeiugrheuighreujigre));
        
        string IMigrationMetadata.Id
        {
            get { return "202105191359072_gorejgiorjeiugrheuighreujigre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
